### PR TITLE
rm contributors from index, add O'Rly cover

### PR DESCRIPTION
**Pull request by vindarel**
https://vindarel.github.io/cl-cookbook/

Does this cover make unanimity ? :)

generated here: https://dev.to/rly

### CODE REVIEW

**Comment by bendudson** [comment]
Like the Lisp Lizard! Looks good, just link ` [comp.lang.lisp][cll].` not rendering. Needs more `( )`?

**Comment by vindarel** [comment]
oops, bad cleanup. Fixed, thanks.

**Comment by pnathan** [comment]
nice

**Comment by sheepduke** [comment]
There is a question mark on the top-right position of the `O RLY` mark.

Is it intended?

**Comment by phoe** [comment]
Yes.

@vindarel I'd capitalize the `the` in the title of the book.

**Comment by vindarel** [comment]
indeed, but a capital `T` makes the title too long thus the last `k` of "Cookbook" disappears :/
https://orly-appstore.herokuapp.com/generate?title=The%20Common%20Lisp%20Cookboo&top_text=Lisp%20series&author=Collective&image_code=19&theme=7&guide_text=Diving%20in&guide_text_placement=bottom_right

**Pull request merged**
