### PR TITLE
Minor fixes for iteration, style guide, front page, etc

### PR DESCRIPTION
**Pull request by cgay**
applies to #540

### CODE REVIEW

**Comment by vindarel** [comment]
that's grand, thanks.

We have to talk about code snippets starting with `* `, I really don't like them: beginners wonder what this is, more tedious to copy-paste, ugly, less explicit than `CL-USER> `. I would not have any prompt (so the styleguide isn't clear on this, but it doesn't mention prompt strings^^).

oh, I see you also uncommented the results, which makes sense when using `* `.

so instead of

```lisp
(map 'vector (lambda (it) (+ it 10)) '(1 2 3))
;; #(11 12 13)
```

we now have

```lisp
* (map 'vector (lambda (it) (+ it 10)) '(1 2 3))
#(11 12 13)
```

this is undoing edits I made for this.

(for long results we can use a `=>` without `;;` afterwards)

**Comment by cgay** [comment]
ok, that makes sense. Just to make sure I understand correctly, you're saying you would prefer

```lisp
(some lisp form)
;; result value 1
;; result value 2
```
?

Or we could go with this, perhaps a little clearer?
```lisp
(some lisp form)
;; => result value 1
;; => result value 2
```

**Comment by vindarel** [comment]
option 1) is used throughout the Cookbook, option 2) is good, we can go with it.

With long results, we can do

```lisp
(some lisp form)
;; =>
;; 1
;; 2
;; 3
```

but also

```lisp
(some lisp form)
;; =>
(some
   result
   form/s)
```

(this allows to see syntax highlighting for the result when appropriate)

and also a separate code block for the result.

**Comment by cgay** [comment]
oh, thanks for merging that. Sorry to have let it slide for so long.

**Pull request merged**
