### PR TITLE
Added an article about function declaration 

### PR DESCRIPTION
**Pull request by Sokolov57**
Mostly taken from http://www.lispworks.com/documentation/lcl50/aug/aug-36.html 
I hope this does not violate any copyright stuff, lispworks doesn't own the square function.
I just added some output for clarity.

### CODE REVIEW

**Comment by sheepduke** [comment]
I should thank you first because `ftype` part is in my TODO list but I was so busy recently...

**Comment by vindarel** [comment]
They don't own the square function, but they own their text, and you copied sentences.

> All Rights Reserved. No part of this publication may be reproduced
http://www.lispworks.com/documentation/lcl50/aug/aug-3.html#HEADING3-0

:/

I think it's best anyways to digest and rewrite the content, to make it even clearer, and create another helpful resource, so people can read lispworks' and this. Thoughts ?

@pnathan ?

**Comment by Sokolov57** [comment]
Yeah, ok, if nobody wishes to do it atm, I'll contribute to this rewriting part in an hour or so. I'm probably not very good at it, so pls check after me.

**Comment by vindarel** [comment]
Thanks for this addition and for rewriting !

**Comment by Sokolov57** [comment]
Well, the declamation -- I used it because it's outside of the scope, that's just how I am used to do this. But I have no authority what to use here, so..

**Comment by vindarel** [comment]
Since @sheepduke approved, all good, thanks !

**Pull request merged**
