### PR TITLE
build executables with ASDF:make, minimize Buildapp

### PR DESCRIPTION
**Pull request by vindarel**
thanks to comments on https://www.reddit.com/r/Common_Lisp/comments/7nlq22/scripting_parsing_command_line_arguments_building/

### CODE REVIEW

**Comment by pnathan** [comment]
dang, nice.

:+1:  from me.

**Comment by vityok** [comment]
[ASDF manual](https://common-lisp.net/project/asdf/asdf.html#Convenience-Functions) says that this functionality is untested and should be used for own risk

**Comment by vindarel** [comment]
> ASDF manual says that this functionality is untested and should be used for own risk

that's right, but it also sounds a usual precaution warning. It worked out of the box for me, Shinmera on reddit says he's been using this for years.

> P.S. and my lisps (CCL/SBCL) leave the compiled binary in the .cache directory

For SBCL are you sure ? I tested, it creates the binary in the right place for me (in the project root alongside the .asd)

**Comment by vityok** [comment]
@vindarel yep, SBCL 1.4.1 when the binrary name is "application.bin" stores the files in the `.cache` directory but not in the project directory. But I'll retest it later to see if it is reliably reproduced.

**Pull request merged**
