### PR TITLE
Add compression level and size comparison

### PR DESCRIPTION
**Pull request by funk443**
Two nice little tables to demonstrate how compression levels and file sizes are related

### CODE REVIEW

**Comment by vindarel** [comment]
Excellent, thanks!

re presentation: it's "MB" in english (yes?), not "MiB".

I read better the columns in the order "compression level" -> "program size"

The markdown table doesn't render well in the epub and pdf :( Could use transform to a HTML table? Like so:

```html

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
}
th {
  text-align: left;
}
</style>

<table>
  <tbody>
    <tr>
      <td>Compression level</td>
      <td>Program size</td>
    </tr>
    <tr>
      <td>Without compression</td>
      <td>46MB</td>
    </tr>
  </tbody>
</table>
```

thanks again

**Comment by funk443** [comment]
Hello!

"MiB" stands for "MebiByte", while "MB" stands for "MegaByte".  I use "MiB" because that's how my system measures the file size.  

And I did put the table in a code block, so that might not be a problem?

**Comment by vindarel** [comment]
TIl about this notation. I used them interchangeably.

sure a simpler code block will do the job very well.

**Comment by funk443** [comment]
So should I convert them into MB?

**Comment by vindarel** [comment]
"should", no, but maybe yes, as it is more common? I thought MiB was a typo, but since it's correct I was accepting it.

**Pull request merged**
