### PR TITLE
arrays.md: fix link for matlisp

### PR DESCRIPTION
**Pull request by ebzzry**

### CODE REVIEW

**Comment by sheepduke** [comment]
Thank you. Professional link fixer ;-)

**Comment by ebzzry** [comment]
Or, what happens when you’ve had too much coffee. ;-)

**Comment by sheepduke** [comment]
> Or, what happens when you’ve had too much coffee. ;-)

Totally understood. That's why I did this:
https://www.reddit.com/r/lisp/comments/bz82gw/an_emacs_snippet_to_add_faces_for_builtin_common/

**Comment by vindarel** [comment]
> too much coffee. ;-)

I wondered if you had a secret ! :p

**Pull request merged**
