### PR TITLE
Add list of communities

### LINKED ISSUE #295: Mention Discord server somewhere?
I joined the server for some time, but I recently found that it is more active than I thought.

https://discordapp.com/channels/297478281278652417

Should it be a good idea to mention it somewhere? So the newbies of Lisp have one more place to ask questions.

Or probably we should add a section to describe where Lisp hackers hang out.

### PR DESCRIPTION
**Pull request by sheepduke**
Closes #295

### CODE REVIEW

**Comment by vindarel** [comment]
why remove lisp-lang.org?

**Comment by phoe** [comment]
https://lisp-lang.org/community/ could perhaps be updated to point to the updated link.

**Comment by sheepduke** [comment]
> why remove lisp-lang.org?

Sorry, I made a mistake...Added back.

**Comment by sheepduke** [comment]
On 2019-12-21 04:27, phoe <notifications@github.com> wrote:
> https://lisp-lang.org/community/ could perhaps be updated to point to the updated link.
>
You see, we have so many different places that hold very similar
information.

I just selected awesome-cl for its ease of communication and
maintenance.

**Pull request merged**
