### PR TITLE
debugging.md: Interactive Trace Dialog

### PR DESCRIPTION
**Pull request by mmontone**
Add documentation about SLIME/SLY Interactive Trace Dialog contrib.

### CODE REVIEW

**Comment by vindarel** [comment]
Super useful!

There's a conflict, I can't merge automatically though.

(and your fix is merged, nice)

**Comment by mmontone** [comment]
I've fixed the conflict . I did it from Github UI, but I hope I got it right.

**Comment by vindarel** [comment]
nah it didn't work. I checked the log of your branch: you were 4 years behind^^ I picked the patches properly.

**Comment by mmontone** [comment]
Oh. Sorry. And thanks. I sync the branches, but I must have forgotten to sync locally or something.

**Pull request closed without merging**
