### PR TITLE
Detailed instructions on initial setup

### PR DESCRIPTION
**Pull request by can3p**
Github uses customized jekyll setup, that goes with bundled dependencies their own markdown implementation etc, so sometimes it's easier to use it instead of stock jekyll.

In addition to the the whole ruby/gems thing can be tricky due to dependencies mismatch and similar thing, so I've added a section to readme with detailed instructions, to make contributing easier.

### CODE REVIEW

**Comment by pnathan** [comment]
please fix conflicts

**Comment by pnathan** [comment]
(this is also a great idea and I will merge once the git issue is untangled)

**Comment by can3p** [comment]
I resolved the conflict using github web interface and now it still shows pull request as broken on this page but as resolve on the page of my fork. What should I do to solve it there as well?

**Comment by pnathan** [comment]
curious. <3 git

**Comment by pnathan** [comment]
:sigh:

**Comment by pnathan** [comment]
thank you for your contribution

**Pull request merged**
