### PR TITLE
Cl21

### PR DESCRIPTION
**Pull request by vindarel**
Pushing for CL21 with an entry at the top.

CL21 is great !

### CODE REVIEW

**Comment by vindarel** [comment]
read it online: https://vindarel.github.io/cl-cookbook/cl21.html

**Comment by pnathan** [comment]
is cl21 that good in pracice? It didn't appeal to me when I first head about it...

**Comment by vindarel** [comment]
Open question since I didn't write large projects. But I really like the map for lists and vectors (instead of `mapcar 'vector`, generic stuff, shorter lambdas, … and everything is appealing to me :p

**Comment by pnathan** [comment]
Let's put this under an "experimental" page heading then until someone
whose used it in a bigger project steps in to remark on it. I get the "just
appealing" factor, but I don't think we should recommend it (since that is
effect what the Cookbook will be doing) as a normative thing.

**Comment by vindarel** [comment]
I'm really keen on advertising this, but I reckon we may not recommend it in a normative thing, for another reason that it is not guaranteed to be stable. I suggest this: we keep it at the top of the index for better visibility, but I changed its link title to "Experimental CL21" (instead of "modern Common Lisp").

**Comment by vindarel** [comment]
Merged, but I can change something if needed :)

**Pull request merged**
