### PR TITLE
Lisp lang icon

### PR DESCRIPTION
**Pull request by vindarel**
I took lisp-lang.org's icon and displayed it on the upper left corner. It's clickable.

PR based on the bootstrap PR: https://github.com/LispCookbook/cl-cookbook/pull/68

landing page: (to redesign ?)

selection_155

Content page: 

selection_156

Just trying.

I like the icon and I think it's ok to use it, isn't it ? (besides I find the projects related in scope)

### CODE REVIEW

**Comment by pnathan** [comment]
What is the license of this file?

Also, shouldn't we contact lisp-lang.org to see if they are ok with our use
of it? It seems that it's not quite polite to use a logo from another
site....

I would think that some time with Gimp and a font library would give us an
icon that is unique to use with easy licensing.

On Jun 21, 2017 6:02 AM, "vindarel" <notifications@github.com> wrote:

I took lisp-lang.org's icon and displayed it on the upper left corner. It's
clickable.

landing page: (to redesign ?)

[image: selection_155]
<https://user-images.githubusercontent.com/3721004/27385202-1276b342-5692-11e7-8d8e-eb309f2e7e94.png>

Content page:

[image: selection_156]
<https://user-images.githubusercontent.com/3721004/27385213-217e1326-5692-11e7-822c-aca7400638e5.png>

Just trying.

I like the icon and I think it's ok to use it, isn't it ? (besides I find
the projects related in scope)
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/LispCookbook/cl-cookbook/pull/69
Commit Summary

   - add jquery 3.2.1
   - add jquery-toc
   - create a TOC on all pages (from h2)
   - Don't write the TOC on the index + ignore the site+page title
   - bootstrap, TOC on the side
   - style: TOC in dark gray, not bootstrap blue
   - fix doubled title "CL Cookbook -- CL Cookbook" on index
   - Added lisp-lang.org's icon on upper left corner

File Changes

   - *M* _layouts/chapter.html
   <https://github.com/LispCookbook/cl-cookbook/pull/69/files#diff-0> (18)
   - *M* _layouts/default.html
   <https://github.com/LispCookbook/cl-cookbook/pull/69/files#diff-1> (40)
   - *A* assets/cl-logo-blue.png
   <https://github.com/LispCookbook/cl-cookbook/pull/69/files#diff-2> (0)
   - *A* assets/jquery-3.2.1.min.js
   <https://github.com/LispCookbook/cl-cookbook/pull/69/files#diff-3> (4)
   - *A* assets/jquery.toc/jquery.toc.js
   <https://github.com/LispCookbook/cl-cookbook/pull/69/files#diff-4> (113)
   - *A* assets/jquery.toc/jquery.toc.min.js
   <https://github.com/LispCookbook/cl-cookbook/pull/69/files#diff-5> (2)
   - *M* assets/style.scss
   <https://github.com/LispCookbook/cl-cookbook/pull/69/files#diff-6> (4)
   - *M* index.md
   <https://github.com/LispCookbook/cl-cookbook/pull/69/files#diff-7> (2)

Patch Links:

   - https://github.com/LispCookbook/cl-cookbook/pull/69.patch
   - https://github.com/LispCookbook/cl-cookbook/pull/69.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LispCookbook/cl-cookbook/pull/69>, or mute the thread

**Comment by eudoxia0** [comment]
The author is my friend. I run lisp-lang.org. let my check what the license
is (I for one am 100% using the same logo)

**Comment by vindarel** [comment]
@eudoxia0 OK thanks (I was expecting you to follow the PRs actually).

But do you both think it makes sense to use it ?

> What is the license of this file? 

it is not specified on github.

**Comment by pnathan** [comment]
Let's ensure the license file is valid for our use before we use it. Maybe check with the author before we use it.

**Comment by eudoxia0** [comment]
Sorry this took so long. My friend released this under Attribution-NonCommercial-NoDerivatives 4.0 International. So no profiting off this logo unless you get his permission!

Go ahead and use it.

**Comment by vindarel** [comment]
that's great, go then !

**Pull request merged**
