### PR TITLE
add Plausible analytics

### PR DESCRIPTION
**Pull request by vindarel**
Hello,

I am curious to see some stat counters. What about you?
I propose to plug Plausible in. It's free software, privacy focused (RGPD compliant), also 

> Made and hosted in the EU
> 100% self-funded and independent

https://plausible.io

I just bought their hosting for one year. 

I will be able to generate a public link to share with you.

---

> Even though the purpose of Plausible Analytics is to track the usage of a website, this can still be done without collecting any personal data or personally identifiable information (PII), without using cookies and while respecting the privacy of your website visitors.

> By using Plausible Analytics, all the site measurement is carried out absolutely anonymously. Cookies are not set and no personal data is collected. All data is in aggregate only. The website owner gets some actionable data to help them learn and improve, while the visitor keeps having a nice and enjoyable experience.

### CODE REVIEW

**Comment by pnathan** [comment]
Github has some analytics built in these days. Have you looked at them?

**Comment by vindarel** [comment]
I had had a look, and it's very simple, and a bit confusing IMO. It mixes views to issues and .md files (actually the pages I presume), and more importantly it doesn't seem to keep the history of last months.

**Comment by vindarel** [comment]
The shared link doesn't work, I opened an issue.

**Comment by vindarel** [comment]
The shared link still wasn't fixed (https://github.com/plausible/analytics/issues/376), but here's a screenshot. Enjoy reading the stats. I particularly like to see what are the most consulted pages. The iteration page looks to be well used, oh yeah I understand why :) 

image

**Comment by vindarel** [comment]
Hello, here's the link: https://plausible.io/share/iHlnXx9AdyjAHzKvPd9Je

**Pull request merged**
