### PR TITLE
[WIP] Jquery TOC

### PR DESCRIPTION
**Pull request by vindarel**
I tried with another plugin: https://github.com/ndabas/toc

it's OK but it also generates it on the landing page (which already has its toc). So, I quickly push but this is to clean.

Good but not as cool as the other plugin with a sidebar:

selection_151

Not good:

selection_150

hello #40

### CODE REVIEW

**Comment by pnathan** [comment]
is there a way we can not have it on the landing page?

or rewrite the landing page to not have the big list?

**Comment by vindarel** [comment]
Done ! No toc on the index, and don't include the page title (always "Common Lisp Cookbook - page title") in it either.

selection_152

We desperately need styling now^^

**Comment by vindarel** [comment]
This plugin may be nice: http://gregfranko.com/jquery.tocify.js/ (on the sidebar, styled, transitions), but no success on my first try.

**Comment by pnathan** [comment]
Are you clear for me to merge this as-is then?

**Comment by vindarel** [comment]
Yes, I confirm this PR.

Also I'll clean and suggest today some bootstrap styling:

selection_153

**Pull request merged**
