### PR TITLE
Web development

### PR DESCRIPTION
**Pull request by vindarel**
for #105 

I have a mixed feeling with this new page. It is needed, it has useful sections (storing passwords, building, deployments,…), it is an overview of a lot of stuff that otherwise need a lot of digging, but it isn't a proper tutorial like other pages. The reader can try the Hunchentoot examples, but not much more. It is also a half-baked Hunchentoot tutorial. I also don't really want to push for a framework, they have their pros and cons, so I wouldn't write a complete tutorial for one of them. That would be the role of another project.

I suggest we merge and complete missing sections (JS, form validation (there is no strong proponent), job queues,…).

https://vindarel.github.io/cl-cookbook/web.html

### CODE REVIEW

**Comment by pnathan** [comment]
:eyes:  I'll stare at it later today when I need a break

**Comment by pnathan** [comment]
> Hunchentoot and Clack are two web servers that you’ll often hear about.

Well, Clack isn't a web server, it's an application framework.

**Comment by pnathan** [comment]
I like it, actually. I think it gives a good start.

**Comment by vindarel** [comment]
> Well, Clack isn't a web server, it's an application framework.

fixed.

Thank you, I'll merge and iterate on it then !

**Pull request merged**
