### PR TITLE
sockets programming (TCP, UDP)

### LINKED ISSUE #177: Rewrite the old sockets section
… which was deleted in 910ea4c2129cef7815eff267991c89839ba8484e and is still visible at http://cl-cookbook.sourceforge.net/sockets.html

usocket: https://common-lisp.net/project/usocket/api-docs.shtml

### PR DESCRIPTION
**Pull request by vindarel**
fixes #177

### CODE REVIEW

**Comment by vindarel** [comment]
Hi @shortsightedsid, I copied your nice guides to TCP and UDP here. Is it fine for you, do you want to author it ?

Thanks

**Comment by vindarel** [comment]
Actually one todo:

> In code that you'd want someone else to read, you should use usocket:with-client-socket and usocket:with-server-socket. usocket:with-client-socket has the additional benefit that it binds a stream variable for you, so you do not need to use the stream accessors.

**Comment by pnathan** [comment]
@vindarel do we want to have this PR hanging open?

**Comment by vindarel** [comment]
I wouldn't merge without showing the `with-client-socket` macro and I can't fix it yet. I added the "help wanted" label on the issue.

**Comment by pnathan** [comment]
@vindarel Do we have the license to use it with modifications? I.e., rewriting the with-client-socket macro to `with-client-socket-simple` or w/e?

**Comment by pnathan** [comment]
ping @vindarel

**Comment by sheepduke** [comment]
@vindarel What is the problem with `with-client-socket`? I tried the following code snippet and it worked as expected.

```lisp
(usocket:with-client-socket
    (socket stream "127.0.0.1" 12321 :element-type 'character)
  (usocket:wait-for-input socket)
  (format t "Input is: ~a~&" (read-line stream))
  (usocket:socket-close socket))
```

**Comment by vindarel** [comment]
There are no problems. I don't know / I am unsure how to replace the actual code with a better one that would use `with-client[-server]-socket`. If you know, you're welcome to make a PR !

**Comment by sheepduke** [comment]
@vindarel Well to be honest I just experimented *after* you made this PR. ;-)

I will try to inspect it if available...

**Pull request merged**
