### PR TITLE
Clos fix

### PR DESCRIPTION
**Pull request by can3p**
First take in #83. Layout is not ideal, but content is mostly converted to markdown. Links are replaced to alive ones if possible.

### CODE REVIEW

**Comment by vindarel** [comment]
Fantastic ! 
Looks great to me.

the actual: https://lispcookbook.github.io/cl-cookbook/clos-tutorial/index.html

VS

selection_161

is it the best indentation though ?

selection_162

**Comment by can3p** [comment]
No, for sure not, I'll work on this part

**Comment by pnathan** [comment]
Lots of thanks for the PR, @can3p - Waiting for the new commit. :)

either myself or @vindarel will merge when your new changes lands

**Comment by can3p** [comment]
ok, code should look better now

**Comment by vindarel** [comment]
Thanks !!

and also to pnathan for the merge rights.

**Pull request merged**
