### PR TITLE
moved 'os', 'process', 'windows' and 'w32' to md

### PR DESCRIPTION
**Pull request by chuchana**
The process/threads chapter is Lispworks-specific. --> [Bordeaux Threads](https://common-lisp.net/project/bordeaux-threads/)?

### CODE REVIEW

**Comment by pnathan** [comment]
@chuchana - Yes. The existing chapter should probably (I only quick-skimmed it) be migrated to LispWorks, and a new chapter started for using Bordeaux Threads.

**Comment by chuchana** [comment]
@pnathan I tried starting to port it without any previous knowledge of Bordeaux-Threads, but I tripped very near the beginning: 
> Before you go any further, you might want to locate the "Process Browser". Aptly enough, you'll find it on the LispWorks podium under the icon of somebody running away. Open one **before** you get into trouble. To kill a process which won't respond to polite coercion, select it in the Process Browser and then click the "skull and crossbones" icon.

I found how to kill a thread that I have assigned to a variable:
` (setf *foo* (bt:make-thread (lambda () (loop)) :name "Foo2"))` --> `(bt:destroy-thread *foo*)`
but not how to kill just any thread that I can see with `(bt:all-threads)`:
`(bt:make-thread (lambda () (loop)) :name "Foo")` --> ?

That has got to be possible too, right?

**Comment by eudoxia0** [comment]
We can investigate that later, we should move to markdown before making too many edits to the content. One step at a time.

**Comment by chuchana** [comment]
I just started locally in a new file, the content I pushed is all original. Is there anything else I can do for the move to markdown?

**Comment by pnathan** [comment]
quick skim LGTM.

**Pull request merged**
