### PR TITLE
Multidimensional arrays page

### PR DESCRIPTION
**Pull request by bendudson**
This partly addresses issue #149, though is probably not ready yet. 

I have made a collection of useful recipes for manipulating standard arrays, rather than choosing one of the many CLOS-based extension libraries. I hope these are more generically useful.

Some of the libraries I've used, array-operations and LLA, have been abandoned by the author (https://tpapp.github.io/post/orphaned-lisp-libraries/), but they were the most convenient, or at least easiest to get working, of the many I looked at. I have adopted array-operations (https://github.com/bendudson/array-operations) and added to it, and will try to improve the documentation for LLA when I figure out how it works. 

Some of the array-operations functions may be found elsewhere, for example `each` is essentially the same as `array-map` from https://stackoverflow.com/questions/4116069/lisp-multidimensional-array-elementwise-operations . I thought it would be better to use a Quicklisp library where possible.

I've included some small utility functions and macros, which I found very useful, and couldn't find elsewhere. Is that ok? They are slightly simplified versions of things I've added to array-operations, but are not in the quicklisp version. I am not very experienced in CL, so these are likely not optimal or in the best style. Comments and improvements welcome!

### CODE REVIEW

**Comment by vindarel** [comment]
Wooo, fantastic resource ! 

> I've included some small utility functions and macros, which I found very useful, and couldn't find elsewhere. Is that ok?

it's ok, and it will be even better when you find a place for them in a QL library :)

About array-operations, I'm sure you could become the new maintainer, did you ask ? He can give you push access or transfer ownership, and you'd have to notify QL by a new issue.

**Comment by vindarel** [comment]
consequently, you could add a note in those snippets that they are in your version of array-operations (they are only a git clone in ql/local-projects after all), generally it's ok to me to advertise your active fork.

**Comment by vindarel** [comment]
Also no mention of CLASP ? Just curious.

**Comment by bendudson** [comment]
I haven't asked him yet, as I haven't been maintaining it long, but it's a good idea and I should ask.
CLASP would be good to add, but I haven't any experience (yet) of using it. It currently requires a compile from source so is probably not very beginner-friendly. I can definitely add a link to it.

**Pull request merged**
